service: monoame-serverless-jsdoc-template
useDotenv: true
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_LOCATION}
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true

functions:
  api:
    handler: src/api/index.handler
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"
    timeout: 15
